[tool.ruff]
line-length = 100
src = ["apps", "services"]

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.pytest.ini_options]
pythonpath = ["libs/python", "apps", "services"]
minversion = "7.0"
